<?php foreach ($checkboxFilters as $current): ?>
<?php
    $current_id = $this->escapeHtmlAttr(str_replace(' ', '', $current['desc']));
    switch ($current_id) {
        case 'local_only':
            $title = ' rel="tooltip" title="'.$this->transEsc('facet_btn_Hover_localOnly').'"';
            break;
        case 'online_only':
            $title = ' rel="tooltip" title="'.$this->transEsc('facet_btn_Hover_onlineOnly').'"';
            break;
        case 'hss_only':
            $title = ' rel="tooltip" title="'.$this->transEsc('facet_btn_Hover_hssOnly').'"';
            break;
        default:
            $title = $modal = '';
    }
?>
  <div class="facet" >
    <a <?=$title?> class="checkbox-filter<?php if(!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<?php endif; ?>" href="<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']);?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>">
      <?php if ($current['selected']): ?>
        <span class="sr-only"><?=$this->transEsc('clear_tag_filter') ?></span>
      <?php endif; ?>
      <span class="text">
        <i class="fa fa-<?=$current['selected'] ? 'check-square-o' : 'square-o' ?>"></i>
        <?=$this->transEsc($current['desc']) ?>
      </span>
      <?php if (!$current['selected']): ?>
        <span class="badge avail-count"></span>
      <?php endif; ?>
    </a>
  </div>
<?php endforeach; ?>
