<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
//    try {
        $holdings = $this->driver->getRealTimeHoldings($this->layout()->userLang);
/*    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }*/
    $hasVols = $this->tab->hasVolumes();
    $volStock = $this->driver->getVolumeStock();
    $formats = $this->driver->getFormats();
    $remarks = $this->driver->getRemarksFromMarc();

    $allppns = [];
    if ($user) {
        $allppns = $this->ils()->getAllPpnsFrom($user);
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>
<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<?php endif; ?>
<?php if ($openUrlActive): ?>
  <?=$openUrl->renderTemplate()?>
<?php endif; ?>
<?php foreach ($holdings['holdings'] as $holding): ?>
<h3>
  <?php $locationText = $this->transEsc('location_' . $holding['location'], [], $holding['location']); ?>
  <?php
    /* JSON Decoding not necessary anymore
    $locationArray = json_decode($holding['location'], true);
    $locationText = $locationArray[strtoupper($this->layout()->userLang)];
    $locationHrefArray = json_decode($holding['locationhref'], true);
    $locationHref = $locationHrefArray[strtoupper($this->layout()->userLang)];
    */
    $locationText = $holding['location'];
    $locationHref = $holding['locationhref'];
  ?>
  <?php if (isset($holding['locationhref']) && $holding['locationhref']): ?>
    <a href="<?=$locationHref?>" target="_blank"><?=$locationText?></a>
  <?php else: ?>
    <?php if ($locationText != 'Unknown'): ?>
      <?=$locationText?>
    <?php endif; ?>
  <?php endif; ?>
</h3>
<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <?php $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
<!--
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td width="80%">
      <?php foreach ($callNos as $callNo): ?>
        <?php if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
        <?php else: ?>
          <?=$this->escapeHtml($callNo)?>
        <?php endif; ?>
        <br />
      <?php endforeach; ?>
    </td>
  </tr>
-->
  <?php endif; ?>
  <?php if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
    <tr>
      <?php // Translation for summary is a special case for backwards-compatibility ?>
      <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
      <td>
        <?php foreach ($textFields as $current): ?>
          <?=$this->escapeHtml($current)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; endif; ?>
  <?php foreach ($holding['items'] as $row): ?>
    <?php
      $idSet = false;
      $row['item_notes'] = []; // reset item_notes to clear the notes from DAIA
      $epnArr = explode(':', $row['item_id']);
      if ($epnArr[(count($epnArr)-2)] == "epn") {
          $epn = $epnArr[(count($epnArr)-1)];
          if (is_array($row['item_notes']) && array_key_exists($epn, $volStock) && is_array($volStock[$epn]) && $volStock[$epn] != null) {
              foreach ($volStock[$epn] as $vs) {
                  if (!in_array($vs, $row['item_notes']) && !empty($vs)) {
                      $idSet = true;
                      $row['item_notes'][] = $vs;
                  }
              }
          }
      }
      if ($epnArr[(count($epnArr)-2)] == "bar") {
          $bar = $epnArr[(count($epnArr)-1)];
          if (is_array($row['item_notes']) && array_key_exists($bar, $volStock) && is_array($volStock[$bar]) && $volStock[$bar] != null) {
              foreach ($volStock[$bar] as $vs) {
                  if (!in_array($vs, $row['item_notes']) && !empty($vs)) {
                      $idSet = true;
                      $row['item_notes'][] = $vs;
                  }
              }
          }
      }
      $pureCallnumberArray = explode(':', $row['callnumber']);
      $pureCallnumber = isset($pureCallnumberArray[1]) ? $pureCallnumberArray[1] : $row['callnumber'];
      if ($idSet == false && is_array($row['item_notes']) && array_key_exists($pureCallnumber, $volStock) && is_array($volStock[$pureCallnumber]) && isset($volStock[$pureCallnumber])) {
          foreach ($volStock[$pureCallnumber] as $vs) {
              if (!in_array($vs, $row['item_notes']) && !empty($vs)) {
                  $row['item_notes'][] = $vs;
              }
          }
      }
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
    ?>
    <?php if ((isset($row['barcode']) && $row['barcode'] != "") || !empty($row['item_notes'][0])): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td width="80%">
          <?php if ($pureCallnumber != "Unknown"): ?>
            <?=$this->transEsc("Call Number")?>: <?=$pureCallnumber?><br/>
          <?php endif; ?>

          <?php if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <?php endif; ?>
          <?php if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <?php else: ?>
            <?php if ($row['availability']): ?>
              <?php if (strlen($row['callnumber']) == 11 && substr($row['callnumber'], 0, 1) == 'D'): ?>
                <span class="text-danger"><?=$this->translate('da_copy')?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <?php elseif (count($row['services']) == count($row['limitation_types']) && count($row['services']) > 0): ?>
                <span class="text-danger"><?=$this->translate('advance_reservation')?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <?php else: ?>
                <?php /* Begin Available Items (Holds) */ ?>
                 <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
                <?php if (isset($row['link']) && $row['link'] && $user && in_array($row['id'], $allppns) == false): ?>
                  <a class="<?=$check ? 'checkRequest ' : ''?>placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-clock-o holdreserve" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
                <?php endif; ?>
                <?php if (isset($row['weblink']) && $row['weblink']): ?>
                  <a href="<?=$this->recordLink()->getRequestUrl($row['weblink'])?>"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;<?=$this->recordLink()->getRequestUrl($row['weblink'])?></a>
                <?php endif; ?>
                <?php if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                  <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest locationInfox holdlink modal-link hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-upload holdorder" aria-hidden="true"></i>&nbsp;<?=$this->transEsc("hold_place")?></a>
                <?php endif; ?>
                <?php if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                  <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
                <?php endif; ?>
                <?php if ((count($row['services']) == '1' || (count($row['services']) > 1 && in_array('loan', $row['services']) === true && count($row['limitation_types']) == 1)) && in_array('presentation', $row['services']) === true && $row['location'] != "Internet" && substr($row['location'], 0, 5) != 'http:' && $hasVols !== true && !in_array('eBook', $formats) && !in_array('Journal', $formats)): ?>
                  <span><?=$this->transEsc('presence_use_only')?></span>
                <?php endif; ?>
              <?php endif; ?>
            <?php else: ?>
              <?php /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <?php if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><?php endif; ?>
              <?php if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <?php endif; ?>
              <?php if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <?php endif; ?>
              <?php if (isset($row['link']) && $row['link'] && in_array($row['id'], $allppns) == false): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> placehold locationInfox holdlink modal-link hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-clock-o holdreserve" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <?php endif; ?>
              <?php if (in_array($row['id'], $allppns) == true): ?>
                  <?=$this->translate("already_reserved_or_lent") ?>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($row['item_notes'])): ?>
              <div class="item-notes">
                <b><?=$this->transEsc("Item Notes")?>:</b>
                <ul>
                  <?php foreach ($row['item_notes'] as $item_note): ?>
                    <li><?=$this->escapeHtml($item_note) ?></li>
                  <?php endforeach; ?>
                </ul>
              </div>
            <?php endif; ?>
          <?php endif; ?>
          <?php /* Embed item structured data: library, barcode, call number */ ?>
          <?php if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <?php endif; ?>
          <?php if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <?php endif; ?>
          <?php if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <?php endif; ?>
          <?php /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
      </tr>
    <?php endif; ?>
  <?php endforeach; ?>
  <?php if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <?php foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<?php endforeach; ?>

<?php if (!empty($urls)): ?>
  <?=$this->transEsc("More links")?><br/>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <span class="externalurl"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><i class="fa fa-download"></i> <?=$this->escapeHtml($current['desc'])?></a></span><br/>
    <?php endforeach; ?>
  <?php endif; ?>
<?php endif; ?>
              <script>
              <?php if ($this->driver->checkInterlibraryLoan() == '1'): ?>
                     // ILL Button
                     loc_button = create_button(href   = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                          hover  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                          text   = '<?=$this->transEsc('interlibrary loan')?>',
                                          icon   = 'fa-truck',
                                          css_classes = 'holdil',
                                          target = '_blank');
                     loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                             loc_code    = 'ext_ill',
                                             link_title  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                             modal_title = '<?=$this->transEsc('loc_modal_Title_ill')?>',
                                             modal_body  = '<?=$this->transEsc('loc_modal_Body_ill')?>',
                                             iframe_src  = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                             modal_foot  = '');
                     document.write(loc_button+loc_modal_link);
               <?php endif; ?>

               <?php if ($this->driver->checkAcquisitionProposal() == '1'): ?>
                     // Aquisition proposal button
                     loc_button = create_button(href   = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                          hover  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                          text   = '<?=$this->transEsc('Erwerbungsvorschlag')?>',
                                          icon   = 'fa-shopping-cart',
                                          css_classes = 'holdwish',
                                          target = '_blank');
                     loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                             loc_code    = 'ext_acqusition',
                                             link_title  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                             modal_title = '<?=$this->transEsc('loc_modal_Title_acqProposal')?>',
                                             modal_body  = '<?=$this->transEsc('loc_modal_Body_acqProposal')?>',
                                             iframe_src  = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                             modal_foot  = '');
                     document.write(loc_button+loc_modal_link);
               <?php endif; ?>
           </script>

<?php if ($hasVols === true): ?>
  <a id="info-<?=$this->driver->getUniqueId() ?>" class="holdlink modal-link hidden-print" title="" rel="tooltip" href="<?=$this->recordLink()->getTabUrl($this->driver, 'TomesVolumes')?>#tabnav" data-original-title="<?=$this->transEsc('loc_modal_Title_multi')?>">
    <i class="fa fa-stack-overflow holdtomes"></i>
    <?=$this->transEsc("See Tomes/Volumes")?>
    <span class="modal-dialog hidden" data-location="Multi" data-title="<?=$this->transEsc('loc_modal_Title_multi')?>"><?=$this->transEsc('loc_modal_Body_multi')?>"></span>
  </a>
<?php endif; ?>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <?php foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <?php endforeach; ?>
</table>
<?php endif; ?>
