<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
  <head>
    <?php $this->headThemeResources(); ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?php
      // Set up OpenSearch link:
      $this->headLink(
        [
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        ]
      );
    ?>
    <!-- RTL styling -->
    <?php if ($this->layout()->rtl) {
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?php
      if (!isset($this->renderingError)) {
        // Add translation strings
        $this->jsTranslations()->addStrings(
          [
            'add_tag_success' => 'add_tag_success',
            'bulk_email_success' => 'bulk_email_success',
            'bulk_noitems_advice' => 'bulk_noitems_advice',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'collection_empty' => 'collection_empty',
            'error_occurred' => 'An error has occurred',
            'go_to_list' => 'go_to_list',
            'hold_available' => 'hold_available',
            'libphonenumber_invalid' => 'libphonenumber_invalid',
            'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
            'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
            'libphonenumber_notanumber' => 'libphonenumber_notanumber',
            'libphonenumber_toolong' => 'libphonenumber_toolong',
            'libphonenumber_tooshort' => 'libphonenumber_tooshort',
            'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
            'loading' => 'Loading',
            'more' => 'more',
            'number_thousands_separator' => [
                'number_thousands_separator', null, ','
            ],
            'sms_success' => 'sms_success'
          ]
        );
        // Add libphonenumber.js strings
        $this->jsTranslations()->addStrings(
          [
            "Phone number invalid" => 'libphonenumber_invalid',
            "Invalid country calling code" => 'libphonenumber_invalidcountry',
            "Invalid region code" => 'libphonenumber_invalidregion',
            "The string supplied did not seem to be a phone number" => 'libphonenumber_notanumber',
            "The string supplied is too long to be a phone number" => 'libphonenumber_toolong',
            "The string supplied is too short to be a phone number" => 'libphonenumber_tooshort',
            "Phone number too short after IDD" => 'libphonenumber_tooshortidd'
          ]
        );
        $this->jsTranslations()->addStrings(
          [
            'loc_btn_Hover_order' => 'loc_btn_Hover_order',
            'loc_modal_Title_order' => 'loc_modal_Title_order',
            'loc_modal_Body_order' => 'loc_modal_Body_order',
            'hold_place' => 'hold_place',
            'loc_modal_Title_reserve_base' => 'loc_modal_Title_reserve_base',
            'loc_modal_Title_reserve' => 'loc_modal_Title_reserve',
            'loc_modal_Title_reservations' => 'loc_modal_Title_reservations',
            'loc_modal_Body_reserve' => 'loc_modal_Body_reserve',
            'recall_this' => 'recall_this',
            'loc_modal_Title_already_taken' => 'loc_modal_Title_already_taken',
            'loc_modal_Body_already_taken' => 'loc_modal_Body_already_taken',
            'already_taken' => 'already_taken',
            'loc_modal_Title_refonly_generic' => 'loc_modal_Title_refonly_generic',
            'loc_btn_Hover_holdings' => 'loc_btn_Hover_holdings',
            'loc_modal_Title_holdings' => 'loc_modal_Title_holdings',
            'see_holdings' => 'see_holdings',
            'loc_modal_Title_eMarc21' => 'loc_modal_Title_eMarc21',
            'infoIcon_Hover' => 'infoIcon_Hover',
            'loc_modal_Body_eMarc21' => 'loc_modal_Body_eMarc21',
            'opclang' => 'opclang',
            'loc_modal_Title_acquired' => 'loc_modal_Title_acquired',
            'loc_modal_Title_service_da' => 'loc_modal_Title_service_da',
            'loc_modal_Body_service_da' => 'loc_modal_Body_service_da',
            'loc_modal_Title_service_ask' => 'loc_modal_Title_service_ask',
            'loc_modal_Body_service_ask' => 'loc_modal_Body_service_ask',
            'loc_modal_Title_temporarily_not_requestable' => 'loc_modal_Title_temporarily_not_requestable',
            'loc_modal_Body_temporarily_not_requestable' => 'loc_modal_Body_temporarily_not_requestable',
            'loc_modal_btn_Hover_temporarily_not_requestable' => 'loc_modal_btn_Hover_temporarily_not_requestable',
            'loc_btn_Hover_restricted' => 'loc_btn_Hover_restricted',
            'loc_modal_Title_restricted' => 'loc_modal_Title_restricted',
            'loc_modal_Body_restricted' => 'loc_modal_Body_restricted',
            'loc_btn_Hover_restricted_fr' => 'loc_btn_Hover_restricted_fr',
            'loc_modal_Title_restricted_fr' => 'loc_modal_Title_restricted_fr',
            'loc_modal_Body_restricted_fr' => 'loc_modal_Body_restricted_fr',
            'loc_modal_Title_service_else' => 'loc_modal_Title_service_else',
            'infoIcon_Hover' => 'infoIcon_Hover',
            'loc_modal_Title_service_else' => 'loc_modal_Title_service_else',
            'loc_modal_Body_service_else' => 'loc_modal_Body_service_else',
            'loc_modal_Title_shelf_generic' => 'loc_modal_Title_shelf_generic',
            'loc_volumes' => $this->transEsc('loc_volumes'),
            'loc_btn_Hover_multi' => $this->transEsc('loc_btn_Hover_multi'),
            'loc_modal_Title_multi' => $this->translate('loc_modal_Title_multi'),
            'loc_modal_Body_multi' => $this->translate('loc_modal_Body_multi'),
            'volume_number' => $this->translate('volume_number'),
            'year' => $this->translate('year'),
            'volume_title' => $this->translate('volume_title'),
            'copies' => $this->translate('copies'),
            'recall_this' => $this->translate('recall_this'),
            'infoIcon_Hover' => $this->translate('infoIcon_Hover'),

            'loc_modal_Title_shelf_generic' => $this->translate('loc_modal_Title_shelf_generic'),
            'loc_modal_Title_refonly_generic' => $this->translate('loc_modal_Title_refonly_generic'),

            'already_taken' => $this->translate('already_taken'),
            'loc_modal_Title_already_taken' => $this->translate('loc_modal_Title_already_taken'),
            'loc_modal_Body_already_taken' => $this->translate('loc_modal_Body_already_taken'),

            'loc_btn_Hover_shelf_lbs' => $this->transEsc('loc_btn_Hover_shelf_lbs'),
            'loc_modal_Title_shelf_lbs' => $this->translate('loc_modal_Title_shelf_lbs'),
            'loc_modal_Body_shelf_lbs' => $this->translate('loc_modal_Body_shelf_lbs'),

            'loc_btn_Hover_shelf_ls1' => $this->transEsc('loc_btn_Hover_shelf_ls1'),
            'loc_modal_Title_shelf_ls1' => $this->translate('loc_modal_Title_shelf_ls1'),
            'loc_modal_Body_shelf_ls1' => $this->translate('loc_modal_Body_shelf_ls1'),

            'loc_btn_Hover_shelf_ls2' => $this->transEsc('loc_btn_Hover_shelf_ls2'),
            'loc_modal_Title_shelf_ls2' => $this->translate('loc_modal_Title_shelf_ls2'),
            'loc_modal_Body_shelf_ls2' => $this->translate('loc_modal_Body_shelf_ls2'),

            'loc_modal_Body_shelf_ls' => $this->translate('loc_modal_Body_shelf_ls'),

            'loc_btn_Hover_sem' => $this->transEsc('loc_btn_Hover_sem'),
            'loc_modal_Title_sem' => $this->translate('loc_modal_Title_sem'),
            'loc_modal_Body_sem' => $this->translate('loc_modal_Body_sem'),

            'loc_btn_Hover_eonly' => $this->translate('loc_btn_Hover_eonly'),
            'loc_modal_Title_eonly' => $this->translate('loc_modal_Title_eonly'),
            'loc_modal_Body_eonly' => $this->translate('loc_modal_Body_eonly'),

            'loc_btn_Hover_eMarc21'   => $this->translate('loc_btn_Hover_eMarc21'),
            'loc_modal_Title_eMarc21' => $this->translate('loc_modal_Title_eMarc21'),
            'loc_modal_Body_eMarc21'  => $this->translate('loc_modal_Body_eMarc21'),
            
            'loc_btn_Hover_tubdok'   => $this->translate('loc_btn_Hover_tubdok'),
            'loc_modal_Title_tubdok' => $this->translate('loc_modal_Title_tubdok'),
            'loc_modal_Body_tubdok'  => $this->translate('loc_modal_Body_tubdok'),

            'loc_btn_Hover_order' => $this->transEsc('loc_btn_Hover_order'),
            'loc_modal_Title_order' => $this->translate('loc_modal_Title_order'),
            'loc_modal_Body_order' => $this->translate('loc_modal_Body_order'),

          ]
        );
        // Deal with cart stuff:
        $cart = $this->cart();
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          if (!empty($domain)) {
            $this->headScript()->appendScript(
              'VuFind.cart.setDomain("' . $domain . '");'
            );
          }
          $cookiePath = $cart->getCookiePath();
          if (!empty($cookiePath)) {
            $this->headScript()->appendScript(
              'VuFind.cart.setCookiePath("' . $cookiePath . '");'
            );
          }
          $this->jsTranslations()->addStrings(
            [
              'addBookBag' => 'Add to Book Bag',
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagStatusFull' => 'bookbag_full',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'removeBookBag' => 'Remove from Book Bag',
              'viewBookBag' => 'View Book Bag'
            ]
          );
        }
        $this->headScript()->prependScript(
          'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // Session keep-alive
      if ($this->keepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->keepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }

      // If account ajax is active, load script and add language strings
      $account = $this->auth()->getManager();
      if ($account->ajaxEnabled()) {
        $this->headScript()->appendFile("account_ajax.js");
        $this->jsTranslations()->addStrings(
          [
            'account_has_alerts' => 'account_has_alerts',
            'Checked Out Items' => 'Checked Out Items',
            'ill_request_available' => 'ill_request_available',
            'renew_item_due_tooltip' => 'renew_item_due_tooltip',
            'renew_item_overdue_tooltip' => 'renew_item_overdue_tooltip',
            'request_in_transit' => 'request_in_transit',
            'storage_retrieval_request_available' => 'storage_retrieval_request_available'
          ]
        );
      }

      $root = rtrim($this->url('home'), '/');
      $translations = $this->jsTranslations()->getJSON();
      $dsb = DEFAULT_SEARCH_BACKEND;
      $setupJS = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.addTranslations({$translations});
JS;
      $this->headScript()->appendScript($setupJS);
    ?>
    <?=$this->headScript()?>

    <?=$this->render('wp_head_'.$this->layout()->userLang.'.phtml')?>
  </head>

<!--  <body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> <?=$this->layoutClass('offcanvas-row')?><?php if ($this->layout()->rtl): ?> rtl<?php endif; ?>"> -->

    <?=$this->render('wp_body_'.$this->layout()->userLang.'.phtml')?>

<div id="primary">
    <?php // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header class="hidden-print">
      <?php if (isset($this->layout()->srmessage)): // message for benefit of screen-reader users ?>
        <span class="sr-only" role="heading" aria-level="1"><?=$this->layout()->srmessage ?></span>
      <?php endif; ?>
      <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
      <?=$this->render('header.phtml')?>
    </header>
    <nav class="breadcrumbs">
      <div class="container">
        <?php if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
          && !empty($this->layout()->breadcrumbs)
          && $this->layout()->breadcrumbs !== false
        ): ?>
          <ul class="breadcrumb hidden-print">
            <?php if(is_array($this->layout()->breadcrumbs)): ?>
              <?php if(count($this->layout()->breadcrumbs) > 1): ?>
                <?=$this->render('breadcrumbs/multi.phtml', [
                    'parents' => $this->layout()->breadcrumbs,
                    'title' => $this->layout()->title,
                    'from' => $this->layout()->from
                  ]) ?>
              <?php else: ?>
                <?=$this->render('breadcrumbs/default.phtml', [
                    'parents' => $this->layout()->breadcrumbs,
                    'title' => $this->layout()->title
                  ]) ?>
              <?php endif; ?>
            <?php else: ?>
              <?=$this->layout()->breadcrumbs ?>
            <?php endif; ?>
          </ul>
        <?php endif; ?>
      </div>
    </nav>
    <div role="main" class="main">
      <div class="container">
        <?=$this->layout()->content ?>
      </div>
    </div>
    <?=$this->render('footer.phtml')?>

    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div class="modal-body"><i class="tub_loading fa fa-circle-o-notch fa-spin"></i> <?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
    <div class="offcanvas-overlay" data-toggle="offcanvas"></div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
    <?php if ($this->recaptcha()->active()): ?>
      <?=$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, "https://www.google.com/recaptcha/api.js?onload=recaptchaOnLoad&render=explicit&hl=" . $this->layout()->userLang, 'SET')?>
    <?php endif; ?>
</div>
  </body>
</html>
