
        <div id="supplementary" class="three">
            <div id="first" class="widget-area" role="complementary">
                <aside id="text-22" class="widget widget_text"><h3 class="widget-title"> </h3>
                    <div class="textwidget"><a href="//www.tub.tuhh.de/en/home/address/" title="Address and directions">TUHH Library<br />
                        Denickestraße 22 J<br />
                        D-21073 Hamburg</a>
                    </div>
                </aside>
            </div>
            <div id="second" class="widget-area" role="complementary">
                <aside id="text-24" class="widget widget_text"><h3 class="widget-title"> </h3>
                    <div class="textwidget">
                        <div class="linklist">
                            <ul>
                                <li><a href="//www.tub.tuhh.de/en/legal-notice">Legal Notice</a></li>
                                <li><a href="//www.tub.tuhh.de/en/data-privacy-statement">Privacy Statement</a></li>
                            </ul>
                        </div>
                    </div>
                </aside>
            </div>
            <div id="third" class="widget-area" role="complementary">
                <aside id="text-20" class="widget widget_text"><h3 class="widget-title"> The Library on </h3>
                    <div class="textwidget">
                        <div style="padding:0em 1em 2.6em 1em ;float:left;">
                            <a href="https://www.facebook.com/TUBHH">
                                <div class="social">
                                    <img style="padding:7px 0px 5px 8px;width:25px;" alt="TUBHH on Facebook" title="TUBHH on Facebook" src="//www.tub.tuhh.de/wp-content/uploads/2012/06/logo-facebook.png" />
                                </div>
                            </a>
                            <a href="https://www.twitter.com/tubhh">
                                <div class="social">
                                    <img style="padding:12px 0px 5px 8px;width:25px;" alt="TUBHH on Twitter" title="TUBHH on Twitter" src="//www.tub.tuhh.de/wp-content/uploads/2012/06/logo-twitter.png" />
                                </div>
                            </a>
                        </div>
                    </div>
                </aside>
            </div>
        </div>