
<div id="supplementary" class="three">
		<div id="first" class="widget-area" role="complementary">
		<aside id="text-11" class="widget widget_text">			<div class="textwidget"><a href="https://www.tub.tuhh.de/adresse/" title="Anfahrt und Lageplan">Universitätsbibliothek der TUHH<br />
Denickestraße 22<br />
D-21073 Hamburg</a></div>
		</aside>	</div><!-- #first .widget-area -->
	
		<div id="second" class="widget-area" role="complementary">
		<aside id="text-12" class="widget widget_text">			<div class="textwidget"><div class="linklist">
<ul>
<li><a href="https://www.tub.tuhh.de/impressum/" title="Impressum der Seite">Impressum</a></li>
<li><a href="https://www.tub.tuhh.de/datenschutz/" title="Datenschutz">Datenschutz</a></li>
</ul>
</div></div>
		</aside>
	</div><!-- #second .widget-area -->
	
		<div id="third" class="widget-area" role="complementary">
		<aside id="text-34" class="widget widget_text">			<div class="textwidget"><div style="padding:0em 0em 2.6em 0em ;float:left;">
    <a href="https://www.facebook.com/TUBHH" target="_blank" title="Die Bibliothek auf Facebook (neues Fenster)" rel="noopener noreferrer">
    <div class="social">
        <img style="padding:7px 0px 5px 8px;width:25px;" alt="Die Bibliothek auf Facebook" title="Die Bibliothek auf Facebook" src="https://www.tub.tuhh.de/wp-content/uploads/2012/06/logo-facebook.png" />
    </div>
    </a>


    <a href="https://www.twitter.com/tubhh" target="_blank" title="Die Bibliothek auf Twitter (neues Fenster)" rel="noopener noreferrer">
    <div class="social">
        <img style="padding:12px 0px 5px 8px;width:25px;"  alt="Die Bibliothek auf Twitter" title="Die Bibliothek auf Twitter"  src="https://www.tub.tuhh.de/wp-content/uploads/2012/06/logo-twitter.png" />
    </div>
    </a>

</div>
</div>
		</aside>	</div><!-- #third .widget-area -->
	</div><!-- #supplementary -->
