
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="geo.region" content="DE-HH" />
<meta name="geo.placename" content="Hamburg" />
<meta name="geo.position" content="53.460997;9.969018" />
<meta name="ICBM" content="53.460997, 9.969018" />
<meta name="google-site-verification" content="hK4rnMGF9skEQjkxGU23LMxG7-YOA0YcDGI1mycTqpk" />
<meta name="google-site-verification" content="w7nvv8Q0aiTJTeXYvKW_t_Z-o8zoQid2wjFfe4Bs1-4" />
<meta name="google-site-verification" content="juvl3McEzhHwPPh-J7zNwwec0_E6c81ZH4are8PlTso" />

<meta name="viewport" content="width=device-width" />

<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="stylesheet" type="text/css" media="all" href="https://www.tub.tuhh.de/wp-content/themes/TUBHH4-twentyeleven-child/style.css" />
<link rel="pingback" href="https://www.tub.tuhh.de/en/xmlrpc.php" />
<link rel="shortcut icon" href="https://www.tub.tuhh.de/wp-content/themes/TUBHH4-twentyeleven-child/images/favicon.ico" />

<!--[if lt IE 9]>
<script src="https://www.tub.tuhh.de/wp-content/themes/twentyeleven/js/html5.js" type="text/javascript"></script>
<![endif]-->

<!-- This site is optimized with the Yoast SEO plugin v13.0 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1"/>
<script type='application/ld+json' class='yoast-schema-graph yoast-schema-graph--main'>{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"https://www.tub.tuhh.de/en/#website","url":"https://www.tub.tuhh.de/en/","name":"Library","potentialAction":{"@type":"SearchAction","target":"https://www.tub.tuhh.de/en/?s={search_term_string}","query-input":"required name=search_term_string"}},{"@type":"WebPage","@id":"#webpage","url":false,"inLanguage":"de-DE","name":"","isPartOf":{"@id":"https://www.tub.tuhh.de/en/#website"}}]}</script>
<!-- / Yoast SEO plugin. -->

<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="Library &raquo; Feed" href="https://www.tub.tuhh.de/en/feed/" />
<link rel="alternate" type="application/rss+xml" title="Library &raquo; Kommentar-Feed" href="https://www.tub.tuhh.de/en/comments/feed/" />
		
<script type='text/javascript'>
/* <![CDATA[ */
var black_studio_touch_dropdown_menu_params = {"selector":"li:has(ul) > a","selector_leaf":"li li li:not(:has(ul)) > a","force_ios5":""};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.tub.tuhh.de/wp-content/plugins/black-studio-touch-dropdown-menu/js/black-studio-touch-dropdown-menu.min.js?ver=1.0.1'></script>
<link rel='https://api.w.org/' href='https://www.tub.tuhh.de/en/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.tub.tuhh.de/en/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.tub.tuhh.de/en/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 5.3.2" />
<link rel="alternate" hreflang="x-default" href="" title="DE |" />
<style type="text/css" media="screen">input#akismet_privacy_check { float: left; margin: 7px 7px 7px 0; width: 13px; }</style><style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style><script type="text/javascript" src="https://www.tub.tuhh.de/wp-content/plugins/si-captcha-for-wordpress/captcha/si_captcha.js?ver=1582244270"></script>
<!-- begin SI CAPTCHA Anti-Spam - login/register form style -->
<style type="text/css">
.si_captcha_small { width:175px; height:45px; padding-top:10px; padding-bottom:10px; }
.si_captcha_large { width:250px; height:60px; padding-top:10px; padding-bottom:10px; }
img#si_image_com { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_reg { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_log { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_side_login { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_checkout { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_jetpack { border-style:none; margin:0; padding-right:5px; float:left; }
img#si_image_bbpress_topic { border-style:none; margin:0; padding-right:5px; float:left; }
.si_captcha_refresh { border-style:none; margin:0; vertical-align:bottom; }
div#si_captcha_input { display:block; padding-top:15px; padding-bottom:5px; }
label#si_captcha_code_label { margin:0; }
input#si_captcha_code_input { width:65px; }
p#si_captcha_code_p { clear: left; padding-top:10px; }
.si-captcha-jetpack-error { color:#DC3232; }
</style>
<!-- end SI CAPTCHA Anti-Spam - login/register form style -->
<style type="text/css">.broken_link, a.broken_link {
	text-decoration: line-through;
}</style><link rel="icon" href="https://www.tub.tuhh.de/en/files/2016/02/cropped-TUB-512px-32x32.png" sizes="32x32" />
<link rel="icon" href="https://www.tub.tuhh.de/en/files/2016/02/cropped-TUB-512px-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="https://www.tub.tuhh.de/en/files/2016/02/cropped-TUB-512px-180x180.png" />
<meta name="msapplication-TileImage" content="https://www.tub.tuhh.de/en/files/2016/02/cropped-TUB-512px-270x270.png" />

<link rel="stylesheet" type="text/css" href="<?=$this->url('home')?>/themes/bootprint3-tub/css/cookieconsent/cookieconsent.min.css" />
<script src="<?=$this->url('home')?>/themes/bootstrap3-tub/js/cookieconsent/cookieconsent.min.js"></script>
<<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#edeff5",
      "text": "#838391"
    },
    "button": {
      "background": "#4b81e8"
    }
  },
  "position": "bottom-right",
  "theme": "classic",
  "content": {
    "message": "<h1>Cookies</h1>This site uses Cookies",
    "dismiss": "Close and accept",
    "link": "Data privacy",
    "href": "https://www.tub.tuhh.de/en/data-privacy"
  }
})});
</script>