<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
?>
<?
  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
    but even if we don't plan to display the link, we still want to get the $openUrl
    value for use in generating a COinS (Z3988) tag -- see bottom of file.
  */
$openUrl = $this->openUrl($this->driver, 'results');
$openUrlActive = $openUrl->isActive();
// Account for replace_other_urls setting
$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
?>
<div class="row result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?>">
  <div class="col-xs-2 left">
    <label class="pull-left"><?=$this->record($this->driver)->getCheckbox() ?></label>
    <input type="hidden" value="<?=$id ?>" class="hiddenId"/>
    <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
      <? if ($summThumb = $this->record($this->driver)->getThumbnail()): ?>
        <img src="<?=$this->escapeHtmlAttr($summThumb)?>" alt="<?=$this->transEsc('Cover Image')?>"/>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>
    </a>
  </div>
  <div class="col-xs-6 middle">
    <div class="resultItemLine1">
      <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
      <?
        $summHighlightedTitle = $this->driver->getHighlightedTitle();
        $summTitle = $this->driver->getTitle();
        if (!empty($summHighlightedTitle)) {
            echo $this->highlight($this->addEllipsis($summHighlightedTitle, $summTitle));
        } else if (!empty($summTitle)) {
            echo $this->escapeHtml($this->truncate($summTitle, 180));
        } else {
            echo $this->transEsc('Title not available');
        }
      ?></a>
    </div>

    <div class="resultItemLine2">
      <? if($this->driver->isCollection()): ?>
        <?=implode('<br>', array_map(array($this, 'escapeHtml'), $this->driver->getSummary())); ?>
      <? else: ?>
        <? $summAuthor = $this->driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
        <?=$this->transEsc('by')?>
        <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?
          $summHighlightedAuthor = $this->driver->getHighlightedAuthor();
          echo !empty($summHighlightedAuthor)
              ? $this->highlight($summHighlightedAuthor)
              : $this->escapeHtml($summAuthor);
        ?></a>
        <? endif; ?>

        <? $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
        <? if (!empty($journalTitle)): ?>
          <?=!empty($summAuthor) ? '<br/>' : ''?>
          <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(array('{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'), '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
          <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
        <? elseif (!empty($summDate)): ?>
          <?=!empty($summAuthor) ? '<br/>' : ''?>
          <?=$this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0])?>
        <? endif; ?>
        <? $summInCollection = $this->driver->getContainingCollections(); if (false && !empty($summInCollection)): ?>
          <? foreach ($summInCollection as $collId => $collText): ?>
            <div>
              <b><?=$this->transEsc("in_collection_label")?></b>
              <a class="collectionLinkText" href="<?=$this->url('collection', array('id' => $collId))?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                <?=$this->escapeHtml($collText)?>
              </a>
            </div>
          <? endforeach; ?>
        <? endif; ?>
      <? endif; ?>
    </div>

    <div class="last">
    <? if(!$this->driver->isCollection()) {
        if ($snippet = $this->driver->getHighlightedSnippet()) {
          if (!empty($snippet['caption'])) {
            echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
          }
          if (!empty($snippet['snippet'])) {
            echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
          }
        }
      } ?>

    <? $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
        $list_id, // get tags for all lists if no single list is selected
        $user_id, 'tag'
       ) : array();
    ?>
    <? if (count($listTags) > 0): ?>
      <strong><?=$this->transEsc('Your Tags')?>:</strong>
      <? $i = 0; foreach ($listTags as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a><? endforeach; ?>
      <br/>
    <? endif; ?>
    <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
    <? if (count($listNotes) > 0): ?>
      <strong><?=$this->transEsc('Notes')?>:</strong>
      <? if (count($listNotes) > 1): ?><br/><? endif; ?>
      <? foreach ($listNotes as $note): ?>
        <?=$this->escapeHtml($note)?><br/>
      <? endforeach; ?>
    <? endif; ?>

    <? if (count($this->lists) > 0): ?>
        <strong><?=$this->transEsc('Saved in')?>:</strong>
        <? $i=0;foreach($this->lists as $current): ?>
            <a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$current->title?></a><? if($i++ < count($this->lists)-1): ?>,<? endif; ?>
        <? endforeach; ?>
        <br/>
    <? endif; ?>
    </div>
  </div>

  <div class="col-xs-2 right">
        <div class="tub_info_topright">
            <?=str_replace('class="', 'class="tub_label tublabel-info ', $this->record($this->driver)->getFormatList())?>
            <?=!empty($summDate) ? '<span class="tub_resYear">' . $this->escapeHtml($summDate[0]) . '</span>' : ''?>
        </div>
        
        <span class="tub_holdingguide">
            <? if ($openUrlActive || !empty($urls)): ?>
                <? if ($openUrlActive): ?>
                    <?=$openUrl->renderTemplate(true)?>
                <? endif; ?>
            <? endif; ?>
            <? if ($this->driver->checkInterlibraryLoan() == '0'): ?>
                <? if ($this->driver->supportsAjaxStatus()): ?>
                    <span class="oa-fulltextes"></span>
                    <span class="holdlocation"><i class="tub_loading fa fa-circle-o-notch fa-spin"></i> <?=$this->transEsc('Loading')?>...</span>
                <? endif; ?>
        <? else: ?>
                <!--@todo: I really don't like it here; it should be in themes/bootstrap3-tub/js/check_item_statuses.js -->
                <script>
                  // ILL Button
                  loc_button = create_button(href   = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                       hover  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                       text   = '<?=$this->transEsc('interlibrary loan')?>',
                                       icon   = 'fa-truck',
                                       css_classes = 'holdil',
                                       target = '_blank');
                  loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                          loc_code    = 'ext_ill',
                                          link_title  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                          modal_title = '<?=$this->transEsc('loc_modal_Title_ill')?>',
                                          modal_body  = '<?=$this->transEsc('loc_modal_Body_ill')?>',
                                          iframe_src  = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                          modal_foot  = '');
                  document.write(loc_button+loc_modal_link);

                  // Aquisition proposal button
                  loc_button = create_button(href   = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                       hover  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                       text   = '<?=$this->transEsc('Erwerbungsvorschlag')?>',
                                       icon   = 'fa-heart',
                                       css_classes = 'holdwish',
                                       target = '_blank');
                  loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                          loc_code    = 'ext_acqusition',
                                          link_title  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                          modal_title = '<?=$this->transEsc('loc_modal_Title_acqProposal')?>',
                                          modal_body  = '<?=$this->transEsc('loc_modal_Body_acqProposal')?>',
                                          iframe_src  = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                          modal_foot  = '');
                  document.write(loc_button+loc_modal_link);
                </script>
            <? endif; ?>
        </span>

      <!-- ORIGINAL POSITION class="supplemental" -->

      <? /* Display qrcode if appropriate: */ ?>
      <? if ($QRCode = $this->record($this->driver)->getQRCode("results")): ?>
        <?
          // Add JS Variables for QrCode
          $this->jsTranslations()->addStrings(array('qrcode_hide' => 'qrcode_hide', 'qrcode_show' => 'qrcode_show'));
        ?>
        <span class="hidden-xs hidden-print">
          <i class="fa fa-qrcode"></i> <a href="<?=$this->escapeHtmlAttr($QRCode);?>" class="qrcodeLink"><?=$this->transEsc('qrcode_show')?></a>
          <div class="qrcode hidden">
            <script type="text/template" class="qrCodeImgTag">
              <img alt="<?=$this->transEsc('QR Code')?>" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
            </script>
          </div><br/>
        </span>
      <? endif; ?>

    <i class="fa fa-edit"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a><br/>
    <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
      $deleteUrl = is_null($list_id)
          ? $this->url('myresearch-favorites')
          : $this->url('userList', array('id' => $list_id));
      $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

      $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
    ?>
    <div class="dropdown">
      <i class="fa fa-trash-o"></i> <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" data-target="#" href="<?=$deleteUrlGet ?>">
        <?=$this->transEsc('Delete') ?>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
        <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeHtmlAttr($id) ?>','source':'<?=$this->escapeHtmlAttr($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>

    <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
  </div>
</div>
