<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLink()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
  if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
      <?=$cover ?>
    </div>
    <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endif; ?>
<div class="result<?php if($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>
  <?=$this->record($this->driver)->getCheckbox()?>
  <div class="media">
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
    <div class="media-body">
      <div class="result-body">
        <div class="resultItemLine1">
          <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
          <?php if (!$missing): ?><a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><?php endif; ?>
            <span class="title"><?=$this->record($this->driver)->getTitleHtml()?></span>
          <?php if (!$missing): ?></a><?php endif; ?>
        </div>

        <div class="resultItemLine2">
          <?php if($this->driver->isCollection()): ?>
            <?=implode('<br>', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); ?>
          <?php else: ?>
            <?php $summAuthors = $this->driver->getPrimaryAuthors(); if (!empty($summAuthors)): ?>
              <?=$this->transEsc('by')?>
              <?php $authorCount = count($summAuthors); foreach ($summAuthors as $i => $summAuthor): ?>
                <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?=$this->escapeHtml($summAuthor)?></a><?=($i + 1 < $authorCount ? ';' : '') ?>
              <?php endforeach; ?>
            <?php endif; ?>

            <?php $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
            <?php if (!empty($journalTitle)): ?>
              <?=!empty($summAuthor) ? '<br/>' : ''?>
              <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
              <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
            <?php elseif (!empty($summDate)): ?>
              <?=!empty($summAuthor) ? '<br/>' : ''?>
              <?=$this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0])?>
            <?php endif; ?>
            <?php $summInCollection = $this->driver->getContainingCollections(); if (false && !empty($summInCollection)): ?>
              <?php foreach ($summInCollection as $collId => $collText): ?>
                <div>
                  <b><?=$this->transEsc("in_collection_label")?></b>
                  <a class="collectionLinkText" href="<?=$this->record($this->driver)->getLink('collection', $collid)?>">
                    <?=$this->escapeHtml($collText)?>
                  </a>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>

        <div class="last">
          <?php if(!$this->driver->isCollection()) {
              if ($snippet = $this->driver->getHighlightedSnippet()) {
                if (!empty($snippet['caption'])) {
                  echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
                }
                if (!empty($snippet['snippet'])) {
                  echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
                }
              }
            } ?>

          <?php $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
              null === $list_id ? true : $list_id, // get tags for all lists if no single list is selected
              $user_id, 'tag'
             ) : [];
          ?>
          <?php if (count($listTags) > 0): ?>
            <strong><?=$this->transEsc('Your Tags')?>:</strong>
            <?php foreach ($listTags as $tag): ?>
              <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a>
            <?php endforeach; ?>
            <br/>
          <?php endif; ?>
          <?php $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
          <?php if (count($listNotes) > 0): ?>
            <strong><?=$this->transEsc('Notes')?>:</strong>
            <?php if (count($listNotes) > 1): ?><br/><?php endif; ?>
            <?php foreach ($listNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br/>
            <?php endforeach; ?>
          <?php endif; ?>

          <?php if (count($this->lists ?? []) > 0): ?>
              <strong><?=$this->transEsc('Saved in')?>:</strong>
              <?php $i = 0;foreach($this->lists as $current): ?>
                  <a href="<?=$this->url('userList', ['id' => $current->id])?>"><?=$this->escapeHtml($current->title)?></a><?php if($i++ < count($this->lists) - 1): ?>,<?php endif; ?>
              <?php endforeach; ?>
              <br/>
          <?php endif; ?>

          <?php /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
                but even if we don't plan to display the link, we still want to get the $openUrl
                value for use in generating a COinS (Z3988) tag -- see bottom of file.
              */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            $doi = $this->doi($this->driver, 'results');
            $doiActive = $doi->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

            if ($openUrlActive || $doiActive || !empty($urls)):
          ?>
            <?php if ($doiActive): ?>
              <br/>
              <?=$doi->renderTemplate()?>
            <?php endif; ?>

            <?php endif; ?>
          <br/>

          <?=$this->record($this->driver)->getFormatList() ?>

          <?=$this->record($this->driver)->getPreviews()?>
        </div>
      </div>

    <div class="col-md-3 col-sm-9 col-xs-8 col-md-offset-0 col-sm-offset-3 col-xs-offset-4 right">
      <div class="hidden-print">
        <i class="fa fa-fw fa-edit" aria-hidden="true"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><?php if (null !== $list_id):?>&amp;list_id=<?=urlencode($list_id)?><?php endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a> 
        <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
          $deleteUrl = null === $list_id
              ? $this->url('myresearch-favorites')
              : $this->url('userList', ['id' => $list_id]);
          $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

          $dLabel = 'delete-label-' . preg_replace('[\W]', '-', $id);
        ?>
        <div class="dropdown">
          <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" href="<?=$deleteUrlGet ?>">
            <?=$this->transEsc('Delete') ?>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
            <li><a id="confirm_delete_item_<?=$this->escapeHtmlAttr($id);?>" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
            <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>

        <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>':''?>
      </div>
        <span class="tub_holdingguide" record-id="<?=$id?>">
            <?php if ($openUrlActive || !empty($urls)): ?>
                <?php if ($openUrlActive): ?>
                    <?=$openUrl->renderTemplate(true)?>
                <?php endif; ?>
            <?php endif; ?>
             <?php if (method_exists($this->driver, 'checkInterlibraryLoan') === true && $this->driver->checkInterlibraryLoan() == '0'): ?>
                <?php if ($this->driver->supportsAjaxStatus()): ?>
                    <span class="oa-fulltextes"></span>
                    <span class="holdlocation"><i class="tub_loading fa fa-circle-o-notch fa-spin"></i> <?=$this->transEsc('Loading')?>...</span>
                <?php endif; ?>
            <?php else: ?>
                <!--@todo: I really don't like it here; it should be in themes/bootstrap3-tub/js/check_item_statuses.js -->
                <script>
                  // ILL Button
                  loc_button = create_button(href   = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                       hover  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                       text   = '<?=$this->transEsc('interlibrary loan')?>',
                                       icon   = 'fa-truck',
                                       css_classes = 'holdil',
                                       target = '_blank');
                  loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                          loc_code    = 'ext_ill',
                                          link_title  = '<?=$this->transEsc('loc_btn_Hover_ill')?>',
                                          modal_title = '<?=$this->transEsc('loc_modal_Title_ill')?>',
                                          modal_body  = '<?=$this->transEsc('loc_modal_Body_ill')?>',
                                          iframe_src  = 'https://gso.gbv.de/request/FORM/LOAN?PPN=<?=$this->driver->getUniqueId() ?>',
                                          modal_foot  = '','','','',
                                          modal_suffix = '-il');
                  document.write(loc_button+loc_modal_link);
                </script>
            <?php endif; ?>

            <?php if (method_exists($this->driver, 'checkAcquisitionProposal') === true && $this->driver->checkAcquisitionProposal() == '1'): ?>
                <script>
                  // Aquisition proposal button
                  loc_button = create_button(href   = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                       hover  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                       text   = '<?=$this->transEsc('Erwerbungsvorschlag')?>',
                                       icon   = 'fa-shopping-cart',
                                       css_classes = 'holdwish',
                                       target = '_blank');
                  loc_modal_link = create_modal(id    = '<?=$this->driver->getUniqueId() ?>',
                                          loc_code    = 'ext_acqusition',
                                          link_title  = '<?=$this->transEsc('loc_btn_Hover_acqProposal')?>',
                                          modal_title = '<?=$this->transEsc('loc_modal_Title_acqProposal')?>',
                                          modal_body  = '<?=$this->transEsc('loc_modal_Body_acqProposal')?>',
                                          iframe_src  = '<?=$this->transEsc('Erwerbungsvorschlag_Url')?><?=$this->driver->getOpenUrl()?>&gvk_ppn=<?=$this->driver->getUniqueId() ?>',
                                          modal_foot  = '','','','',
                                          modal_suffix = '-ap');
                  document.write(loc_button+loc_modal_link);
                </script>
            <?php endif; ?>
        </span>
        <?php if ($this->driver->supportsAjaxStatus()): ?>
          <span class="status ajax-availability hidden">
            <!--<span class="label label-default"><?=$this->transEsc('Loading')?>...</span>-->
          </span>
        <?php endif; ?>
</div>

    </div>
    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
  </div>
</div>
<?php
$escId = $this->escapeJs($id);
$escSource = $this->escapeJs($source);
$script = <<<JS
$('#confirm_delete_item_${escId}').click(function(e) {
    e.preventDefault();
    $.post('${deleteUrl}', {
                'delete':'${escId}',
                'source':'${escSource}',
                'confirm':true
            },
            function(){
                location.reload()
            }
        );
});
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
