<?php $editions = $this->related->getResults(); if (!empty($editions)): ?>
  <h4><?=$this->transEsc('Other Editions')?></h4>
  <ul class="nav nav-list open">
    <?php foreach ($editions as $data): ?>
      <li style="padding-top: 10px; font-size:smaller;">
        <i class="tub_lielement fa fa-angle-right" style="margin-left:-21px;"></i>
        <?php $formats = $data->getFormats(); if (count($formats) > 0): ?>
          <span class="<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>">
        <?php else: ?>
          <span>
        <?php endif; ?>
        <a href="<?=$this->recordLink()->getUrl($data)?>">
        <?php
            $t = $data->getTitle();
            $s = $t;
            if (is_array($t) === true) {
                $s = $t[0];
            }
        ?>
        <?=$this->escapeHtml($s)?>
        </a>
        </span>
        <?php $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
          <br/><?=$this->transEsc('By')?>: <?=$this->escapeHtml($author);?>
        <?php endif; ?>
        <?php $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          <?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
